### ISSUE TITLE
irpp_mensuel_salarie > 0 pour ouvrière à 427 TND par mois

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-tunisia#84]
Afin de tester `openjibaya`, je tente de construire un test utilisant les variables dont a besoin `openjibaya` sur les données issues de la fiche de paie ouvrière.

Je m'attends à ce que ce test YAML passe :
```
- name: OpenJibaya sur cas ouvrière
  reforms: 
    - openfisca_tunisia.reforms.de_net_a_salaire_de_base.de_net_a_salaire_de_base
  period: 2016-02
  absolute_error_margin: 1
  input:
    salaire_net_a_payer: 427.040
    primes: 6.080 + 47.500
    
  output:
    irpp_mensuel_salarie: 0 # déduit de ouvriere_2016_02.yaml
    salaire_imposable: 427.040
    
    cotisations_salarie: -43.164 # cnss
    salaire_de_base: 416.624
    
    assiette_cotisations_sociales: 470.204 # brut

    # salaire_super_brut: 427.040 + 0 + 43.164 + 6.080 + 47.500 + cotisations_employeur
```
Les variables qui m'intéressent pour `openjibaya` sont donc les outputs.
Mais le test ne passe pas. J'obtiens différents KO en commençant par : 
```
AssertionError: In test 'OpenJibaya sur cas ouvrière', in file '/Users/sch/Dev/github/tunisie/openfisca-tunisia/tests/reforms/test_salaire.yaml', irpp_mensuel_salarie@2016-02: [-45.468124] differs from 0.0 with an absolute margin [45.468124] > 1
```

Où est l'erreur ?
Serait-ce aussi lié au `regime_securite_sociale` de l'ouvrière ? 🤔
